WIP: Met 29 documentation
ministryofjustice/opg-metrics pull request #11
Opened 2021-02-02 13:56 UTC by johnnolan

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes Ticket: ####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2021-02-03 14:58 UTC, johnnolan commented
Note for me, squash and merge this PR

2021-02-03 16:09 UTC, mattmachell requested changes
See inline comments for a few suggestions.

2021-02-03 16:09 UTC, mattmachell commented on ABOUT_THIS_SERVICE.md
> +* Encourage and Gamify the culture of celebrating maintenance and managing legacy
Not sure Gamify is an aim.

2021-02-03 16:09 UTC, mattmachell commented on ABOUT_THIS_SERVICE.md
> +This service is not intended to be a place where you debug issues or store logs that you can diagnose problems. It is to enable you to pass key bits of information across multiple services so you can
Feel like it needs something about how it should be comprehensible to non-technical staff to make decisions or kickstart investigations..

2021-02-03 16:09 UTC, mattmachell commented on LICENCE
> +Copyright (c) 2014 Ministry of Justice
2021

2021-02-03 16:48 UTC, mattmachell approved these changes

2021-02-03 16:48 UTC, mattmachell commented on ABOUT_THIS_SERVICE.md
> +The end result should be a visualisation that will enable all professions to be able to identify changes in the service and act together.
Top phrasing! 👍

2021-02-04 14:28 UTC, mattmachell approved these changes

2021-02-09 08:44 UTC, charlesmmarshall commented on README.md
> +`brew install --cask aws-vault`
Is it worth linking out to https://docs.opg.service.justice.gov.uk/documentation/get_started.html#get-started

2021-02-09 08:51 UTC, charlesmmarshall approved these changes

2021-02-09 09:10 UTC, charlesmmarshall approved these changes

2021-02-09 09:22 UTC, merged